version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  app:
    build: ./hello
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=hello_dev
      - PGHOST=db
      - PGPORT=5432
    depends_on:
      - "db"
      - "grafana"
    ports:
      - 4000:4000

  prometheus:
    image: prom/prometheus:v2.37.0
    # For the sake of a smoother project running experience, prometheus will run
    # as root to avoid permission errors. This is not recommended and the
    # approach would be to use sudo and chown to change the prometheus-data
    # permissions on the host side.
    user: root
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:8.2.0
    volumes:
      - ./grafana-data:/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    depends_on:
      - "prometheus"

    user: '104'
